version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: payments
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: payments

	payments:
		build: .
		image: chamaconekt/payments
		links:
		- postgres
		container_name: payments
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- payments
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/payments-nginx/nginx.conf
		depends_on:
			- payments
		ports:
			- 80:80
		volumes_from:
			- payments

volumes:
	payments-static-files:
		driver:local